on:
  push:
    tags:
      - v*

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        shell: pwsh
        run: |
          ./Build.ps1
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}